### ISSUE TITLE
NPE in AddIfDirective

### ISSUE THREAD

**Issue by yegor256** [yegor256/xembly#34]
```
java.lang.NullPointerException
	at org.xembly.AddIfDirective.exec(AddIfDirective.java:81)
	at org.xembly.Xembler.apply_aroundBody0(Xembler.java:132)
	at org.xembly.Xembler$AjcClosure1.run(Xembler.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:204)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:160)
	at org.xembly.Xembler.apply_aroundBody2(Xembler.java:128)
	at org.xembly.Xembler$AjcClosure3.run(Xembler.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:130)
	at org.xembly.Xembler.apply(Xembler.java:128)
```

I have no idea why this happens..

**Comment by php-coder** [comment]
Please, reassign it to someone else.

**Comment by yegor256** [comment]
@davvd give this to someone else pls

**Comment by davvd** [comment]
> @davvd Please, reassign it to someone else.

@php-coder right, I'll try to find someone else for this task

**Comment by davvd** [comment]
> @davvd give this to someone else pls

@yegor256 I'll ask somebody else to pick this up

**Comment by davvd** [comment]
@apocarteres please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by apocarteres** [comment]
ok. will take a look

**Comment by apocarteres** [comment]
I've managed to reproduce it. Basically, it's intermittent issue connected with concurrency. As far as i can see <code>org.xembly.Xembler</code> originally designed as non-thread-safe. Thus there are two options now:

1. inform users that Xembler is not thread-safe and delegate responsibility to them to handle such cases
2. get Xembler a thread-safe

Sample concurrent code introduced on screenshot. It's 100% breaks Xembler with NPE or sometimes with other runtime exception.

Please take a look at let me know which options is preferred next.

![screen shot 2015-01-02 at 8 48 08 pm](https://cloud.githubusercontent.com/assets/3305624/5596809/ee50310e-92b8-11e4-8e47-56d15e647548.png)

**Comment by yegor256** [comment]
@apocarteres nice catch! I would recommend to add a unit test that reproduces the issue and proves that `Xembler` is not thread-safe. Then, `@Ignore` the test and add a `@todo` puzzle to it, asking for a solution. That will be enough for this task. Later we'll fix the code. More about PDD/puzzles: http://www.yegor256.com/2009/03/04/pdd.html

**Comment by apocarteres** [comment]
roger that

**Comment by apocarteres** [comment]
well, pull request has been initiated / CI tests look good. is anyone able to approve?

**Comment by yegor256** [comment]
@apocarteres you did everything correct, give us some time to review your PR and merge it

**Comment by apocarteres** [comment]
nps

**Comment by apocarteres** [comment]
raised PR with codestyle fix. check it pls

**Comment by apocarteres** [comment]
@yegor256 can you review/merge it, pls?

**Comment by yegor256** [comment]
thanks!

**Comment by davvd** [comment]
@apocarteres **30 mins** added to your account (payment number `50344771`), many thanks for your contribution!; added +30 to your rating, now it is equal to [+0](http://www.netbout.com/b/35111?open=rating)
