### ISSUE TITLE
NS to set namespace

### ISSUE THREAD

**Issue by yegor256** [yegor256/xembly#4]
Let's add `NS` directive to set a namespace of a node

**Comment by davvd** [comment]
@darkled you're working with this issue for 13 days already... -30 added to your rating, current score is: [+30](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@davvd please, assign this task to someone else

**Comment by davvd** [comment]
> @davvd please, assign this task to someone else

@darkled right, I will find someone else, no problem

**Comment by davvd** [comment]
@darkled you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, current score is: [-195](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@davvd @yegor256 I am not sure these -60 are correct since I've rejected the issue 3 days ago. Am I wrong?

**Comment by davvd** [comment]
@jenya please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@dpisarenko it's yours, please go ahead

**Comment by dpisarenko** [comment]
@davvd Please find someone to review my PR https://github.com/yegor256/xembly/pull/50 .

**Comment by dpisarenko** [comment]
@yegor256 The PR was merged, please close this issue. Thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.20`

**Comment by yegor256** [comment]
@dpisarenko thanks!

**Comment by davvd** [comment]
@dpisarenko I added **30 mins** to your account, many thanks for working with the project!; added +30 to your rating, now it is equal to [+626](http://www.netbout.com/b/35089?open=rating)
