### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [yegor256/xembly#46]
Copyright part in license sections still features 2014.

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@maurezen many thanks for the report, I topped your account for 15 mins, transaction 49978537

**Comment by davvd** [comment]
@romankisilenko can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close this issue.

**Comment by davvd** [comment]
@romankisilenko thanks, paid, **30 mins** to your account, payment ID is `50614491`

+30 added to your rating, current score is: +150
