### ISSUE TITLE
Missing license config in pom.xml

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/xembly#49]
Please put `<license>file:${basedir}/LICENSE.txt</license>` into the `pom.xml` of xembly, otherwise we'll be getting checkstyle errors (no header) upon fresh checkout.

**Comment by maurezen** [comment]
This is a known bug of qulice configuration in parent-0.31 (jcabi/jcabi-parent#19). I suggest upgrading the parent version to 0.31.1, which contains the fix.

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@dpisarenko thanks for the ticket, your account was topped for 15 mins, payment 50593083

**Comment by davvd** [comment]
@maurezen the task is yours please proceed

**Comment by maurezen** [comment]
@dpisarenko how comes that there is already a license added? I see a sneak commit in #50. 
Anyway, updated the parent and removed the license from xembly config in

@davvd  pull request #51

**Comment by dpisarenko** [comment]
@maurezen Probably I added it to run `mvn qulice:check -Pqulice` locally.

**Comment by dpisarenko** [comment]
@maurezen No, I don't think you should submit PR #51 because then the exact error I had will occur. At https://github.com/yegor256/xembly/pull/51/files I see that you removed `<license>file:${basedir}/LICENSE.txt</license>` from the POM and this was exactly the problem.

**Comment by maurezen** [comment]
@dpisarenko I also changed the parent version, which now has this exact configuration snippet on the parent level in a correct place, so xembly will inherit it. Therefore, no more need to declare explicitly on a child level.

**Comment by dpisarenko** [comment]
@maurezen Alright then. I'll close the issue when PR #51 is merged.

**Comment by maurezen** [comment]
@dpisarenko pull request #51 merged, please close.

**Comment by maurezen** [comment]
@davvd the task is already closed.

**Comment by davvd** [comment]
@maurezen Thanks for your contribution, **30 mins** was added to your account, payment ID is `51287972`

+30 added to your rating, current score is: [+960](http://www.netbout.com/b/35102?open=rating)
