### ISSUE TITLE
Provide "shaded" jar to prevent lib conflicting, e.g. antlr

### ISSUE THREAD

**Issue by tan9** [yegor256/xembly#56]
Our production server has antlr2 in application server level, so applications using xembly encounters following problem:

```
19:50:46,932 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/brt].[appServlet]] (http-/10.2.153.11:8080-40) JBWEB000236: Servlet.service() for servlet appServlet threw exception: java.lang.ClassNotFoundException: org.antlr.runtime.RecognitionException from [Module "deployment.brt-webapp-1.0.0-SNAPSHOT.war:main" from Service Module Loader]
at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:426) [jboss-modules.jar:1.2.2.Final-redhat-1]
at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:374) [jboss-modules.jar:1.2.2.Final-redhat-1]
at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:119) [jboss-modules.jar:1.2.2.Final-redhat-1]
at package.to.my.Service.makeXml(Service.java:354) [brt-service-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```
Where line 354 of Service.java is:
```java
Directives directives = new Directives().add("list");
```
Can you provide an shaded jar with libraries bundled and repackaged, as what they did in [Kryo](https://github.com/EsotericSoftware/kryo#integration-with-maven) ?

**Comment by yegor256** [comment]
@rultor release, tag is `0.21`

**Comment by yegor256** [comment]
@tan9 it's done, take a look: http://www.xembly.org/shaded-jar.html

**Comment by tan9** [comment]
@yegor256 , thank you for the quick response.

The shaded version works very well in our environment. However, I noticed that the shaded dependency wasn't repackaged, and as my understand to ClassLoader hierarchy, seems there are antlr v2 classes from our server level lib coexists with bundled antlr v3's org.antlr.runtime.RecognitionException at the same time.
I am wondering that our site works just because of we didn't use the wonderful Xembly script, hence the antlr lexer, parser is not used in our case.

**Comment by yegor256** [comment]
@tan9 as far as I understand antlr2 classes should not conflict with antlr3 classes, they are in different packages. Or I'm wrong?

**Comment by tan9** [comment]
@yegor256 , you are right, they are in different package and different maven groupd!
That's my fault, since our packaging script filtering out libraries from WARs by using simply file name matching. Both antlr-2* and antlr93* were stripped in the artifact built.

**Comment by yegor256** [comment]
@tan9 I'm glad the problem is solved. please close the ticket if that's it :)
