### ISSUE TITLE
set() for xsd:dateTime

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xembly#65]
Right now Xembly allows set only text content to the node. 
It would be great add a new method `set(java.util.Date)` which convert the param into XML date representation ISO 8601, see http://www.w3.org/TR/xmlschema-2/#isoformats before set.
It will make code more clean.

**Comment by yegor256** [comment]
@dmzaytsev well, I think it's outside of scope of xembly. What format will this method use? There are many ISO 8601 formats... which one will we use?

**Comment by dmzaytsev** [comment]
@yegor256 you are right, the date requirements may be different
I'm closing this
