### ISSUE TITLE
can't add an element/attribute with a namespace into Directives 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xembly#66]
At the moment adding an element/attribute with a namespace into Directives not implemented. I believe it has to be.

@yegor256 ~~could you suggest right now  any workaround to add an attr with a namespace to an element using Directivies ?~~ I did it

**Comment by yegor256** [comment]
@dmzaytsev what's wrong about just `attr("xs:type", "string")` (for example)?

**Comment by dmzaytsev** [comment]
@yegor256 also I need add the namespace declaration to the root element.
I expect if I use `attr("name", "string", "ns")` then Xembler should add the namespace declaration to the root element and generate a prefix for it.
I make Directivies in several places and then compile them into one xml, I have to remember about a namespace declarations.

**Comment by yegor256** [comment]
@dmzaytsev than maybe it's better to add a validation. if you do `attr("xs:type", "string")`, we will check whether this `xs:` prefix is actually defined in the document. if not, you will get a runtime exception. make sense?

**Comment by dmzaytsev** [comment]
@yegor256  a validation is good idea.
but let's imagine if  I should generate a document
```
<doc xmlns:ns0="www.google.com/1">
    <element1>
        <ns0:element2/>
        <ns0:element3/>
    </element1>
</doc>
```
A developer made a Directivies with `.add("ns0:element1")` in one class
and `.add("ns2:element2")`  in another class

I agree Xembly will report about indeclared `ns2`, but how I should  guess which namespace the developer meant when he/she used prefix `ns2` ?

**Comment by yegor256** [comment]
@dmzaytsev got it, make sense, thanks

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `59134418`

**Comment by carlosmiranda** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/xembly/issues/66#issuecomment-411988406))

@carlosmiranda Job [#66](https://github.com/yegor256/xembly/issues/66) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/xembly/issues/66#issuecomment-411988406))

@carlosmiranda Thanks for your contribution, @dmzaytsev[/z](https://www.0crat.com/u/dmzaytsev)! If you would be a member of [the project](https://www.0crat.com/p/CBD1V4118), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by javadev** [comment]
```
<doc xmlns:ns0="www.google.com/1">
    <element1>
        <ns0:element2/>
        <ns0:element3/>
    </element1>
</doc>
```

May be stored as

```
{
  "doc": {
    "-xmlns:ns0": "www.google.com/1",
    "element1": {
      "ns0:element2": {
        "-self-closing": "true"
      },
      "ns0:element3": {
        "-self-closing": "true"
      }
    }
  },
  "#omit-xml-declaration": "yes"
}
```

https://xmltojson.github.io/

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@dmzaytsev I'm closing this, since there will no fix

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#66](https://github.com/yegor256/xembly/issues/66); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
