### ISSUE TITLE
short way to add xsi:nil not implemented 

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/xembly#67]
At the moment `Directives` hasn't a method to add xsi:nil attribute
http://www.w3.org/TR/xmlschema-1/#xsi_nil
I think it can be `nil()` method. It should add attribute `xsi:nil="true"` to current element and add xsi namespace declaration `xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"` to the root element

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@dmzaytsev why can't you just use `.attr("xsi:nil", "true")`?

**Comment by dmzaytsev** [comment]
@yegor256 it's related to  #66
I should add the namespace declaration for the xsi namespace..

```java
.add("root").add("name").nil().up()
```

looks better then 
```java
.add("root").attr("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
.add("name").attr("xsi:nil", "true")
.up()
```
isn't it ?

**Comment by yegor256** [comment]
@dmzaytsev yes, looks nicer, but Xembly is not supposed to be suitable for all possible cases. It's a generic language, with just a few primitive basic operations/commands. Even though the suggestion is nice, it's out of scope.
