### ISSUE TITLE
Docx Read

### ISSUE THREAD

**Issue by amorenew** [yegor256/xembly#74]
Hi
there is no library to read and write docx files in android
so i want to make my own library to android but the only one do this is jaxb
jaxb not work on android
is this library work on android ?
is it good to read docx xml files ?
part of xmls in docx content attached
[document.xml.zip](https://github.com/yegor256/xembly/files/90102/document.xml.zip)

**Comment by yegor256** [comment]
@amorenew yes, this library works on Android. if you will have any issues with Android, let us know and submit new tickets. we'll fix.
