### ISSUE TITLE
Multi node creation with one single statement

### ISSUE THREAD

**Issue by micfra** [yegor256/xembly#76]
Hi, do you think it is possible to add a kind of batch creation of nodes like `XADD 'A/B/C'` which traverses the tree from the current node along the path creating unknown node on its way? Would be a great thing for me! BR Michael

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@micfra not a bad idea... but I think that will make our interface too "rich". you can implement it on your level, just by calling `ADD` multiple times. we have to keep the interface as small as possible. more about this philosophy here: http://www.yegor256.com/2016/04/26/why-inputstream-design-is-wrong.html
