### ISSUE TITLE
Build by rultor failed

### ISSUE THREAD

**Issue by janczer** [yegor256/xembly#78]
When I run build locally everything ok:

```
$ mvn clean install -Pxembly -Pqulice --errors
.....
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.680 s
[INFO] Finished at: 2018-01-10T18:26:05+01:00
[INFO] Final Memory: 47M/781M
[INFO] ------------------------------------------------------------------------
```

But in PR #77 something goes wrong.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#78` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#78](https://github.com/yegor256/xembly/issues/78) was not in scope
