### ISSUE TITLE
Is there a tool like JAXB's `xjc`?

### ISSUE THREAD

**Issue by chhh** [yegor256/xembly#79]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@chhh try `Directives.copyOf(node)`. It will create Xembly directives from an existing XML node.

**Comment by chhh** [comment]
@yegor256 I don't see how that helps. The `xjc` program can generate java classes from an XML schema (XSD) as well as marshallers/unmarshallers. If I understand correctly, `Directives.copyOf(node)` is a way to re-create/insert an existing node into a document.

**Comment by yegor256** [comment]
@chhh what are you trying to achieve? If you need a java class from XML, you need JAXB tools, Xembly won't help here.

**Comment by chhh** [comment]
I wanted better/faster marshallers and unmarshallers for XML data that adheres to some XSD schema.  

Sorry, I got to this repo by stumbling upon this post: http://www.yegor256.com/2015/03/26/jaxb-vs-xembly.html. I didn't read it, but thought this project was a replacement for JAXB that "does it wrong". Sorry to bother.

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#79` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#79](https://github.com/yegor256/xembly/issues/79) was not in scope
