### ISSUE TITLE
How do I add xsi:schemaLocation?

### ISSUE THREAD

**Issue by llorllale** [yegor256/xembly#80]
**What I'm trying to do**
Declare the schema for an XML document that I'm building. This means adding `xsi:schemaLocation` to an element.

**What I actually see**
I cannot find how to do this in the documentation. The `NS` directive appears to be irrelevant. The docs for `Directives.attr` do not seem to indicate that it can be used for this.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale see how it's done in this test https://github.com/yegor256/xembly/blob/0.22/src/test/java/org/xembly/DirectivesTest.java#L284-L294 (and other test methods in this class)

**Comment by llorllale** [comment]
@yegor256 I see, thanks.

I feel that the javadoc for `Directives.attr` should include a short note saying that this is possible.
