### ISSUE TITLE
Windows builds fail with Maven >=3.3.1

### ISSUE THREAD

**Issue by carlosmiranda** [yegor256/xembly#88]
```
[INFO] --- maven-invoker-plugin:1.9:run (default) @ xembly ---
[INFO] Building: saxon\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\dev-tools\apache-maven-3.5.2\bin\mvn.bat
[INFO] Building: xerces\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\dev-tools\apache-maven-3.5.2\bin\mvn.bat
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  saxon\pom.xml
[ERROR] *  xerces\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.964 s
[INFO] Finished at: 2018-08-10T15:38:41+08:00
[INFO] Final Memory: 47M/719M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:1.9:run (default) on project xembly: 2 builds failed. See console output above for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

In Maven 3.3.1, the Maven executable for windows was changed from `mvn.bat` to `mvn.cmd`, so Invoker now fails.

Xembly currently inherits `maven-invoker-plugin:1.9` from `com.jcabi:parent`. The issue is fixed in [version 1.10](https://blog.soebes.de/blog/2015/04/03/apache-maven-invoker-plugin-version-1-dot-10-released/), so upgrading will probably fix this. However, the project is about two years or so behind in terms of library updates, so be mindful that jumping straight into the latest `parent` will probably break a lot of things,

**Comment by 0crat** [comment]
Job [#88](https://github.com/yegor256/xembly/issues/88) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
fixed

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `DEV` is banned at [#88](https://github.com/yegor256/xembly/issues/88); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))
