### ISSUE TITLE
let's use Aibolit static analyzer

### ISSUE THREAD

**Issue by yegor256** [yegor256/xembly#98]
Let's use it: https://github.com/cqfn/aibolit

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.24.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#98` is not assigned, can't get performer
